[agent]
local = false
snapshot_interval = 30
snapshot_path = "snapshots/agent_snapshot.bin"

[xray]
enabled = true
xray_config_path = "/etc/xray/config.json"

[wg]
enabled = true
port = 51820
interface = "wg0"
# privkey и address обычно лучше через env, но можно и тут

[h2]
enabled = false
path = "etc/frkn/h2.yaml"

[mtproto]
enabled = true
port = 8443
secret = "dd00112233445566778899aabbccddeeff"

[metrics]
enabled = true
publisher = "tcp://api-server-ip:5555"
interval = 10

[api]
endpoint = "https://api.frkn.org"
token = "your-super-secret-api-token"

[logging]
level = "warn"

[zmq]
endpoint = "tcp://api-server-ip:3000"
