[node]
env = "experimental"
uuid = "ab514c21-aaaa-bbbb-91f7-32f8cb1aaaaa"
hostname = "darkmachine.frkn.local"
address = "192.168.1.100"
label = "🏴‍☠️ Darkmachine"
max_bandwidth_bps = 1000000000
country = "RU"
type = "common"


[agent]
local = false
snapshot_interval = 30
snapshot_path = "snapshots/agent_snapshot.bin"

[xray]
enabled = true
xray_config_path = "/etc/xray/config.json"

[wg]
enabled = true
port = 51820
interface = "wg0"

[h2]
enabled = false
path = "etc/frkn/h2.yaml"

[mtproto]
enabled = true
port = 8443
secret = "dd00112233445566778899aabbccddeeff"

[metrics]
enabled = true
publisher = "tcp://api-server-ip:5555"
interval = 10

[api]
endpoint = "https://api.frkn.org"
token = "your-super-secret-api-token"

[logging]
level = "warn"

[zmq]
endpoint = "tcp://api-server-ip:3000"
