[carbon]
#address = "10.0.0.1:2003"

[app]
#env = "dev"
#hostname = "localhost"
iface = "en0"
#metrics_delay = 1

[xray]
enabled = true
vmess_port = 8081
vless_port = 2053
ss_port = 1080

[wg]
enabled = true
#port = 51820

[logging]
#level = "info"  
#file = "pony.log"

