[api]
address = "0.0.0.0"
port = 3005
token = "your-super-secret-api-token"
db_sync_interval_sec = 300
subscription_restore_interval = 60
subscription_expire_interval = 60
max_points = 100000000
retention_seconds = 604800 # 7 days

[metrics]
reciever = "tcp://0.0.0.0:3001"
topic = ["metrics"]

[node]
env = "experimental"
label = "🏴‍☠️ DarkMachine"
max_bandwidth_bps = 1000000000 #1gbps

[logging]
level = "debug"

[zmq]
endpoint = "tcp://*:3000"

[pg]
host = "localhost"
port = 5432
db = "frkn_db"
username = "postgres"
password = "password"
