[service]
snapshot_interval = 60
snapshot_path = "snapshots/snapshot-agent.bin"
log_velel = "debug"
updates_endpoint_zmq = "tcp://localhost:3001"

[metrics]
interval = 100
publisher = "tcp://localhost:3002"

[xray]
enabled = true
path = "dev/xray-config.json"

[h2]
enabled = true
path = "dev/h2.yaml"

[wg]
enabled =  false
path = "dev/utun7.conf"

[mtproto]
enabled = true
path = "dev/teleproxy.toml"

[node]
env = "experimental"
uuid = "ab514c21-aaaa-bbbb-cccc-32f8cb1ada40"
hostname = "darkmachine2.frkn.local"
default_interface = "ens0"
address = "192.168.1.100"
label = "Darkmachine 🏴‍☠️ "
max_bandwidth_bps = 1000000000
country = "RU"
type = "common"

[api]
endpoint = "http://127.0.0.1:3000"
token = "supetsecrettoken"
