[carbon]
address = "10.0.0.1:2003"

[app]
env = "dev"
hostname = "localhost"
iface = "en0"
xray_vmess_port = 8081
xray_vless_port = 2053
xray_ss_port = 1080
metrics_delay = 1

[logging]
level = "info"  
file = "pony.log"

