FROM rust:latest AS builder
WORKDIR /app
COPY . .

RUN apt-get update && apt-get install -y protobuf-compiler && \
    cargo build --bin bot --no-default-features --features bot --release

FROM rust:latest
COPY --from=builder /app/target/release/bot /app/bot
COPY --from=builder /app/config-bot-example.toml /app/config.toml
WORKDIR /app
CMD ["./bot", "--config", "config.toml"]
