version: '3.8'

services:
  pony-api:
    image: frknorg/pony-api:latest
    container_name: pony-api
    ports:
      - 3000:3000
    networks:
      - mynetwork
    volumes:
      - ./config-api.toml:/app/config.toml
    command: ["/app/api", "--config", "/app/config.toml"]

  pony-bot:
    image: frknorg/pony-bot:latest
    container_name: pony-bot
    ports:
      - 3000:3000
    networks:
      - mynetwork
    volumes:
      - ./config-bot.toml:/app/config.toml
    command: ["/app/api", "--config", "/app/config.toml"]

networks:
  mynetwork:
    driver: bridge
