[Interface]
PrivateKey = gPUrecCLMjr1S7Q4/9LeroOQUlpmAcSiuv31qsbsUFc=
Address = 10.0.0.1/16
DNS = 1.1.1.1
ListenPort = 51821



[Peer]
PublicKey = 0wAoJhT0lxWVhdw7L2na3gM9NybBNgNSQPknNTpnqEk=
Endpoint = 78.17.28.66:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
