#!/bin/bash -e

PONY_VERSION="${PONY_VERSION:-v0.1.11}"
INSTALL_DIR="/opt/vpn"
ARCH=$(uname -m)
AGENT_URL="https://github.com/frkn-dev/pony/releases/download/$PONY_VERSION/agent-$ARCH"


systemctl stop agent

cd $INSTALL_DIR

echo "Installing agent version $PONY_VERSION..."
echo "$AGENT_URL"
curl -L -o agent "$AGENT_URL"
chmod +x agent

systemctl start agent
